name = "rhythm90-api"
main = "src/backend/index.ts"
compatibility_date = "2025-07-09"
compatibility_flags = ["nodejs_compat"]

[vars]
OPENAI_API_KEY = ""
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""

[[d1_databases]]
binding = "DB"
database_name = "rhythm90-db"
database_id = "73d8857c-97f9-4cfa-800a-225d7346be67" 